eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: "api-gateway"
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}

        - id: customer-service
          uri: http://localhost:8032
          predicates:
            - Path=/customer-service/**
          filters:
            - RewritePath=/customer-service(?<segment>/?.*), $\{segment}

        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/payment-service/**
          filters:
            - RewritePath=/payment-service(?<segment>/?.*), $\{segment}

        - id: plant-service
          uri: http://localhost:8082
          predicates:
            - Path=/plant-service/**
          filters:
            - RewritePath=/plant-service(?<segment>/?.*), $\{segment}

        - id: registration-service
          uri: http://localhost:8083
          predicates:
            - Path=/registration-service/**
          filters:
            - RewritePath=/registration-service(?<segment>/?.*), $\{segment}

        - id: product-webapp
          uri: http://localhost:4200
          predicates:
            - Path=/**
          filters:
            - RewritePath=(?<segment>/?.*), $\{segment}
